#!/usr/bin/with-contenv bash

# check for lock file to only run git operations once
if [ ! -e /lock.file ]; then
  # give abc a sudo shell for development
  echo "auth       sufficient   pam_shells.so" > /etc/pam.d/chsh
  chsh abc -s /bin/bash
  sed -e 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/g' \
    -i /etc/sudoers
else
  # lock exists not importing project this is a restart
  echo "Lock exists just starting cloud9"
fi

# create lock file after first run
touch /lock.file
